import streamlit as st
import pandas as pd
import plotly.express as px
import os

# --- Configuration ---
st.set_page_config(page_title="Fee Analysis Dashboard", layout="wide")

@st.cache_data
def load_data():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(current_dir, 'Fee.csv')
    
    if not os.path.exists(file_path):
        st.error(f"Cannot find the file at: {file_path}")
        st.stop()
        
    df = pd.read_csv(file_path, low_memory=False)
    
    # Exclude specific payment methods
    excluded_methods = ['AMEX', 'UNIONPAYINTERNATIONAL']
    df = df[~df['Payment Method'].isin(excluded_methods)]
    
    # Fill NA in key categorical columns
    cat_cols = ['Payment Method', 'Card Type', 'Region', 'Processing Channel Name', 'Card Category', 'Action Type']
    for col in cat_cols:
        if col in df.columns:
            df[col] = df[col].fillna('Unknown')
            
    # --- Reverse Calculate GMV ---
    df['Amount'] = 0.0
    df['Absolute Fee Cost'] = df['Total Amount in Holding Currency'].abs()
    mask = df['Breakdown Type'] == 'Premium Variable Fee'
    df.loc[mask, 'Amount'] = df.loc[mask, 'Absolute Fee Cost'] / 0.0001
    
    return df

# Load the data
df = load_data()

# --- Sidebar Filters ---
st.sidebar.header("Data Filters")

def get_dropdown_options(series):
    return ["All"] + sorted(series.unique().tolist())

selected_scheme = st.sidebar.selectbox("Card Scheme (Payment Method)", options=get_dropdown_options(df['Payment Method']))
selected_card_type = st.sidebar.selectbox("Card Type", options=get_dropdown_options(df['Card Type']))
selected_region = st.sidebar.selectbox("Regionality", options=get_dropdown_options(df['Region']))
selected_channel = st.sidebar.selectbox("Vertical (Channel)", options=get_dropdown_options(df['Processing Channel Name']))

# --- Apply Filters ---
filtered_df = df.copy()

if selected_scheme != "All":
    filtered_df = filtered_df[filtered_df['Payment Method'] == selected_scheme]
if selected_card_type != "All":
    filtered_df = filtered_df[filtered_df['Card Type'] == selected_card_type]
if selected_region != "All":
    filtered_df = filtered_df[filtered_df['Region'] == selected_region]
if selected_channel != "All":
    filtered_df = filtered_df[filtered_df['Processing Channel Name'] == selected_channel]

# Create a high-level fee category
filtered_df['Fee Category'] = filtered_df['Breakdown Type'].apply(lambda x: str(x).split(' ')[0])

# --- KPIs ---
st.title("💸 Payment Fee Analysis & GMV Dashboard")
st.markdown("Analyzing provider fees based on reverse-calculated Transaction Amounts.")

total_gmv = filtered_df['Amount'].sum()
total_fees = filtered_df['Absolute Fee Cost'].sum()
blended_fee_pct = (total_fees / total_gmv * 100) if total_gmv > 0 else 0

col1, col2, col3 = st.columns(3)
col1.metric("Total Calculated Global GMV (HKD)", f"{total_gmv:,.2f}")
col2.metric("Total Fees (HKD)", f"{total_fees:,.2f}")
col3.metric("Blended Fee %", f"{blended_fee_pct:.4f} %")

st.markdown("---")

# ==========================================
# --- NEW: Unified Visa & MC Summary     ---
# ==========================================
st.subheader("📊 Visa & Mastercard Summary")
st.markdown("Breakdown of core fees over the specific GMV generated by that subset.")

# 1. Filter for Visa and Mastercard
visa_df = filtered_df[filtered_df['Payment Method'].str.upper() == 'VISA']
mc_df = filtered_df[filtered_df['Payment Method'].str.upper() == 'MASTERCARD']

# 2. Calculate their respective GMVs and Share of Total Global GMV
visa_gmv = visa_df['Amount'].sum()
mc_gmv = mc_df['Amount'].sum()

visa_share = (visa_gmv / total_gmv * 100) if total_gmv > 0 else 0
mc_share = (mc_gmv / total_gmv * 100) if total_gmv > 0 else 0

# 3. Display Sub-Headers for Scheme Overalls
hc1, hc2 = st.columns(2)
hc1.metric("VISA Overall GMV", f"{visa_gmv:,.2f}", f"{visa_share:.2f}% Share of Total GMV", delta_color="off")
hc2.metric("MASTERCARD Overall GMV", f"{mc_gmv:,.2f}", f"{mc_share:.2f}% Share of Total GMV", delta_color="off")

st.markdown("")

# 4. Builder Function for the Unified Table
def build_summary_df(df_subset, scheme_name, group_cols, group_name="Overall"):
    if df_subset.empty:
        return pd.DataFrame()
        
    # Group by dimension
    if group_cols:
        res_df = df_subset.groupby(group_cols)['Amount'].sum().reset_index()
        # Clean naming (e.g., "Region: Domestic")
        res_df['Breakdown'] = group_cols[0] + ": " + res_df[group_cols[0]].astype(str)
        res_df.drop(columns=[group_cols[0]], inplace=True)
        res_df.rename(columns={'Amount': 'Subset GMV'}, inplace=True)
    else:
        res_df = pd.DataFrame([{'Breakdown': group_name, 'Subset GMV': df_subset['Amount'].sum()}])
        
    # Calculate Total Fees
    if group_cols:
        tot_fees = df_subset.groupby(group_cols)['Absolute Fee Cost'].sum().reset_index()
        tot_fees['Breakdown'] = group_cols[0] + ": " + tot_fees[group_cols[0]].astype(str)
        res_df = pd.merge(res_df, tot_fees[['Breakdown', 'Absolute Fee Cost']], on='Breakdown', how='left')
        res_df.rename(columns={'Absolute Fee Cost': 'Total Fee Cost'}, inplace=True)
    else:
        res_df['Total Fee Cost'] = df_subset['Absolute Fee Cost'].sum()

    # Calculate Categorical Fees (Interchange, Gateway, etc.)
    if group_cols:
        cat_fees = df_subset.groupby(group_cols + ['Fee Category'])['Absolute Fee Cost'].sum().reset_index()
        cat_fees['Breakdown'] = group_cols[0] + ": " + cat_fees[group_cols[0]].astype(str)
        pivot = cat_fees.pivot(index='Breakdown', columns='Fee Category', values='Absolute Fee Cost').fillna(0).reset_index()
    else:
        cat_fees = df_subset.groupby('Fee Category')['Absolute Fee Cost'].sum().reset_index()
        cat_fees['Breakdown'] = group_name
        pivot = cat_fees.pivot(index='Breakdown', columns='Fee Category', values='Absolute Fee Cost').fillna(0).reset_index()
        
    res_df = pd.merge(res_df, pivot, on='Breakdown', how='left').fillna(0)
    
    # 5. Format Output Table
    final_df = pd.DataFrame()
    final_df['Scheme'] = [scheme_name] * len(res_df) # Scheme in the first column!
    final_df['Breakdown'] = res_df['Breakdown']
    final_df['GMV (HKD)'] = res_df['Subset GMV'].map("{:,.2f}".format)
    
    # Share of Total Global GMV
    if total_gmv > 0:
        final_df['Share of Total GMV'] = (res_df['Subset GMV'] / total_gmv * 100).map("{:.2f}%".format)
    else:
        final_df['Share of Total GMV'] = "0.00%"
    
    safe_gmv = res_df['Subset GMV'].replace(0, 1)
    
    # Cost % on Subset
    final_df['Total Cost %'] = (res_df['Total Fee Cost'] / safe_gmv * 100).map("{:.4f}%".format)
    
    for col in ['Interchange', 'Scheme', 'Gateway', 'Premium']:
        if col in res_df.columns:
            final_df[f"{col} %"] = (res_df[col] / safe_gmv * 100).map("{:.4f}%".format)
        else:
            final_df[f"{col} %"] = "0.0000%"
            
    # Weighted Cost % (Contribution to Blended Total)
    if total_gmv > 0:
        final_df['Weighted Cost %'] = (res_df['Total Fee Cost'] / total_gmv * 100).map("{:.4f}%".format)
    else:
        final_df['Weighted Cost %'] = "0.0000%"
            
    return final_df

# Combine Visa & MC into one table
summary_dfs = []
for scheme_name, sdf in [('VISA', visa_df), ('MASTERCARD', mc_df)]:
    if not sdf.empty:
        summary_dfs.append(build_summary_df(sdf, scheme_name, [], group_name="Overall"))
        summary_dfs.append(build_summary_df(sdf, scheme_name, ['Region']))
        summary_dfs.append(build_summary_df(sdf, scheme_name, ['Card Type']))

if summary_dfs:
    combined_summary = pd.concat(summary_dfs, ignore_index=True)
    st.dataframe(combined_summary, use_container_width=True)
else:
    st.info("No Visa or Mastercard data available with the current filters.")

st.markdown("---")

# ==========================================
# --- Original Fees vs Total GMV Tables ---
# ==========================================
st.subheader("Fees Breakdown vs Total GMV")

summary_table = filtered_df.groupby('Breakdown Type').agg(
    Fee_Cost=('Absolute Fee Cost', 'sum'),
).reset_index()

if total_gmv > 0:
    summary_table['% of Total GMV'] = (summary_table['Fee_Cost'] / total_gmv) * 100
    summary_table['% of Total Fees'] = (summary_table['Fee_Cost'] / total_fees) * 100
else:
    summary_table['% of Total GMV'] = 0.0
    summary_table['% of Total Fees'] = 0.0

summary_table = summary_table.sort_values(by='Fee_Cost', ascending=False)

display_table = summary_table.copy()
display_table['Fee_Cost'] = display_table['Fee_Cost'].map("{:,.2f}".format)
display_table['% of Total GMV'] = display_table['% of Total GMV'].map("{:.4f}%".format)
display_table['% of Total Fees'] = display_table['% of Total Fees'].map("{:.2f}%".format)

st.dataframe(display_table, use_container_width=True)

with st.expander("View Detailed Breakdown by Fee Detail"):
    detail_table = filtered_df.groupby(['Breakdown Type', 'Fee Detail'], dropna=False).agg(
        Fee_Cost=('Absolute Fee Cost', 'sum')
    ).reset_index()
    
    detail_table['Fee Detail'] = detail_table['Fee Detail'].fillna('N/A')
    
    if total_gmv > 0:
        detail_table['% of Total GMV'] = (detail_table['Fee_Cost'] / total_gmv) * 100
    else:
        detail_table['% of Total GMV'] = 0.0
        
    detail_table = detail_table.sort_values(by='Fee_Cost', ascending=False)
    detail_table['Fee_Cost'] = detail_table['Fee_Cost'].map("{:,.2f}".format)
    detail_table['% of Total GMV'] = detail_table['% of Total GMV'].map("{:.4f}%".format)
    st.dataframe(detail_table, use_container_width=True)

# --- Charts ---
st.subheader("Visual Insights")
c1, c2 = st.columns(2)

with c1:
    fig_pie = px.pie(summary_table, values='Fee_Cost', names='Breakdown Type', title="Fee Distribution by Type", hole=0.4)
    st.plotly_chart(fig_pie, use_container_width=True)

with c2:
    fig_bar = px.bar(summary_table, x='Breakdown Type', y='Fee_Cost', title="Total Fees by Breakdown Type", text_auto='.2s')
    st.plotly_chart(fig_bar, use_container_width=True)
