import streamlit as st
import pandas as pd
import plotly.express as px
import os

# --- Configuration ---
st.set_page_config(page_title="Fee Analysis Dashboard", layout="wide")

@st.cache_data
def load_data():
    # Find file safely
    current_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(current_dir, 'Fee.csv')
    
    if not os.path.exists(file_path):
        st.error(f"Cannot find the file at: {file_path}")
        st.stop()
        
    df = pd.read_csv(file_path, low_memory=False)
    
    # Exclude specific payment methods
    excluded_methods = ['AMEX', 'UNIONPAYINTERNATIONAL']
    df = df[~df['Payment Method'].isin(excluded_methods)]
    
    # Fill NA in key categorical columns
    cat_cols = ['Payment Method', 'Card Type', 'Region', 'Processing Channel Name', 'Card Category', 'Action Type']
    for col in cat_cols:
        if col in df.columns:
            df[col] = df[col].fillna('Unknown')
            
    # --- Reverse Calculate GMV ---
    df['Amount'] = 0.0
    df['Absolute Fee Cost'] = df['Total Amount in Holding Currency'].abs()
    mask = df['Breakdown Type'] == 'Premium Variable Fee'
    df.loc[mask, 'Amount'] = df.loc[mask, 'Absolute Fee Cost'] / 0.0001
    
    return df

# Load the data
df = load_data()

# --- Sidebar Filters ---
st.sidebar.header("Data Filters")

def get_dropdown_options(series):
    return ["All"] + sorted(series.unique().tolist())

selected_scheme = st.sidebar.selectbox("Card Scheme (Payment Method)", options=get_dropdown_options(df['Payment Method']))
selected_card_type = st.sidebar.selectbox("Card Type", options=get_dropdown_options(df['Card Type']))
selected_region = st.sidebar.selectbox("Regionality", options=get_dropdown_options(df['Region']))
selected_channel = st.sidebar.selectbox("Vertical (Channel)", options=get_dropdown_options(df['Processing Channel Name']))

# --- Apply Filters ---
filtered_df = df.copy()

if selected_scheme != "All":
    filtered_df = filtered_df[filtered_df['Payment Method'] == selected_scheme]
if selected_card_type != "All":
    filtered_df = filtered_df[filtered_df['Card Type'] == selected_card_type]
if selected_region != "All":
    filtered_df = filtered_df[filtered_df['Region'] == selected_region]
if selected_channel != "All":
    filtered_df = filtered_df[filtered_df['Processing Channel Name'] == selected_channel]

# Create a high-level fee category (e.g., 'Scheme Fixed Fee' -> 'Scheme')
filtered_df['Fee Category'] = filtered_df['Breakdown Type'].apply(lambda x: str(x).split(' ')[0])

# --- KPIs ---
st.title("💸 Payment Fee Analysis & GMV Dashboard")
st.markdown("Analyzing provider fees based on reverse-calculated Transaction Amounts.")

total_gmv = filtered_df['Amount'].sum()
total_fees = filtered_df['Absolute Fee Cost'].sum()
blended_fee_pct = (total_fees / total_gmv * 100) if total_gmv > 0 else 0

col1, col2, col3 = st.columns(3)
col1.metric("Total Calculated GMV (HKD)", f"{total_gmv:,.2f}")
col2.metric("Total Fees (HKD)", f"{total_fees:,.2f}")
col3.metric("Blended Fee %", f"{blended_fee_pct:.4f} %")

st.markdown("---")

# ==========================================
# --- NEW: Static Summary for Visa & MC  ---
# ==========================================
st.subheader("📊 Visa & Mastercard Summary (% of Respective GMV)")
st.markdown("Breakdown of core fees over the specific GMV generated by that subset.")

def build_summary_df(df_subset, group_cols, group_name="Overall"):
    if df_subset.empty:
        return pd.DataFrame()
        
    # 1. Calculate Subset GMV
    if group_cols:
        res_df = df_subset.groupby(group_cols)['Amount'].sum().reset_index()
        res_df.rename(columns={group_cols[0]: 'Breakdown', 'Amount': 'Subset GMV'}, inplace=True)
    else:
        res_df = pd.DataFrame([{'Breakdown': group_name, 'Subset GMV': df_subset['Amount'].sum()}])
        
    # 2. Calculate Total Fees for Subset
    if group_cols:
        tot_fees = df_subset.groupby(group_cols)['Absolute Fee Cost'].sum().reset_index()
        res_df['Total Fee Cost'] = tot_fees['Absolute Fee Cost']
    else:
        res_df['Total Fee Cost'] = df_subset['Absolute Fee Cost'].sum()

    # 3. Calculate Categorical Fees (Interchange, Scheme, etc)
    if group_cols:
        cat_fees = df_subset.groupby(group_cols + ['Fee Category'])['Absolute Fee Cost'].sum().reset_index()
        pivot = cat_fees.pivot(index=group_cols[0], columns='Fee Category', values='Absolute Fee Cost').fillna(0).reset_index()
        pivot.rename(columns={group_cols[0]: 'Breakdown'}, inplace=True)
    else:
        cat_fees = df_subset.groupby('Fee Category')['Absolute Fee Cost'].sum().reset_index()
        cat_fees['Breakdown'] = group_name
        pivot = cat_fees.pivot(index='Breakdown', columns='Fee Category', values='Absolute Fee Cost').fillna(0).reset_index()
        
    # Merge and format
    res_df = pd.merge(res_df, pivot, on='Breakdown', how='left').fillna(0)
    
    final_df = pd.DataFrame()
    final_df['Breakdown'] = res_df['Breakdown']
    final_df['GMV (HKD)'] = res_df['Subset GMV'].map("{:,.2f}".format)
    
    # Safe division to prevent errors if GMV is 0
    safe_gmv = res_df['Subset GMV'].replace(0, 1)
    
    final_df['Total %'] = (res_df['Total Fee Cost'] / safe_gmv * 100).map("{:.4f}%".format)
    
    # Add standardized column %s (matches Checkout.com typical fees)
    for col in ['Interchange', 'Scheme', 'Gateway', 'Premium']:
        if col in res_df.columns:
            final_df[f"{col} %"] = (res_df[col] / safe_gmv * 100).map("{:.4f}%".format)
        else:
            final_df[f"{col} %"] = "0.0000%"
            
    return final_df

# Generate table for VISA and MASTERCARD side-by-side or stacked
for scheme in ['VISA', 'MASTERCARD']:
    # Ensure matching regardless of uppercase/lowercase in your raw data
    scheme_df = filtered_df[filtered_df['Payment Method'].str.upper() == scheme]
    
    if not scheme_df.empty:
        st.markdown(f"**{scheme}**")
        
        # Build the three views (Overall, by Region, by Card Type)
        df_overall = build_summary_df(scheme_df, [], group_name="Overall")
        df_region = build_summary_df(scheme_df, ['Region'])
        df_card = build_summary_df(scheme_df, ['Card Type'])
        
        # Combine them into one neat table
        combined = pd.concat([df_overall, df_region, df_card], ignore_index=True)
        st.dataframe(combined, use_container_width=True)

st.markdown("---")

# ==========================================
# --- Original Fees vs Total GMV Tables ---
# ==========================================
st.subheader("Fees Breakdown vs Total GMV")

summary_table = filtered_df.groupby('Breakdown Type').agg(
    Fee_Cost=('Absolute Fee Cost', 'sum'),
).reset_index()

if total_gmv > 0:
    summary_table['% of Total GMV'] = (summary_table['Fee_Cost'] / total_gmv) * 100
    summary_table['% of Total Fees'] = (summary_table['Fee_Cost'] / total_fees) * 100
else:
    summary_table['% of Total GMV'] = 0.0
    summary_table['% of Total Fees'] = 0.0

summary_table = summary_table.sort_values(by='Fee_Cost', ascending=False)

display_table = summary_table.copy()
display_table['Fee_Cost'] = display_table['Fee_Cost'].map("{:,.2f}".format)
display_table['% of Total GMV'] = display_table['% of Total GMV'].map("{:.4f}%".format)
display_table['% of Total Fees'] = display_table['% of Total Fees'].map("{:.2f}%".format)

st.dataframe(display_table, use_container_width=True)

with st.expander("View Detailed Breakdown by Fee Detail"):
    detail_table = filtered_df.groupby(['Breakdown Type', 'Fee Detail'], dropna=False).agg(
        Fee_Cost=('Absolute Fee Cost', 'sum')
    ).reset_index()
    
    detail_table['Fee Detail'] = detail_table['Fee Detail'].fillna('N/A')
    
    if total_gmv > 0:
        detail_table['% of Total GMV'] = (detail_table['Fee_Cost'] / total_gmv) * 100
    else:
        detail_table['% of Total GMV'] = 0.0
        
    detail_table = detail_table.sort_values(by='Fee_Cost', ascending=False)
    detail_table['Fee_Cost'] = detail_table['Fee_Cost'].map("{:,.2f}".format)
    detail_table['% of Total GMV'] = detail_table['% of Total GMV'].map("{:.4f}%".format)
    st.dataframe(detail_table, use_container_width=True)

# --- Charts ---
st.subheader("Visual Insights")
c1, c2 = st.columns(2)

with c1:
    fig_pie = px.pie(summary_table, values='Fee_Cost', names='Breakdown Type', title="Fee Distribution by Type", hole=0.4)
    st.plotly_chart(fig_pie, use_container_width=True)

with c2:
    fig_bar = px.bar(summary_table, x='Breakdown Type', y='Fee_Cost', title="Total Fees by Breakdown Type", text_auto='.2s')
    st.plotly_chart(fig_bar, use_container_width=True)
